// <auto-generated />
using System;
using Cmdb.Database;
using Cmdb.Database.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cmdb.Database.Migrations
{
    [DbContext(typeof(CmdbDbContext))]
    [Migration("20260927200138_Search")]
    partial class Search
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cable_medium", new[] { "fiber", "copper", "coax", "power" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "channel_kind", new[] { "wavelength", "timeslot", "vlan" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "circuit_layer", new[] { "physical", "transmission", "logical" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "connection_kind", new[] { "patch", "splice", "termination", "internal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "lifecycle_state", new[] { "planned", "under_construction", "in_service", "decommissioning", "removed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "terminal_kind", new[] { "port", "conductor_end" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cmdb.Database.Model.Cable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("ASiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("a_site_id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes")
                        .HasDefaultValueSql("'{}'");

                    b.Property<long>("BSiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("b_site_id");

                    b.Property<long>("CableTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cable_type_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<LineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(LineString, 3006)")
                        .HasColumnName("geom");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<double>("LengthM")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("double precision")
                        .HasColumnName("length_m")
                        .HasComputedColumnSql("ST_Length(geom)", true);

                    b.Property<LifecycleState>("Lifecycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("lifecycle_state")
                        .HasDefaultValue(LifecycleState.Planned)
                        .HasColumnName("lifecycle");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_cable");

                    b.HasIndex("ASiteId")
                        .HasDatabaseName("ix_cable_a_site_id");

                    b.HasIndex("BSiteId")
                        .HasDatabaseName("ix_cable_b_site_id");

                    b.HasIndex("CableTypeId")
                        .HasDatabaseName("ix_cable_cable_type_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cable_code");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_cable_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex(new[] { "Code" }, "ix_cable_code_pattern")
                        .HasDatabaseName("ix_cable_code_pattern");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Code" }, "ix_cable_code_pattern"), new[] { "text_pattern_ops" });

                    b.HasIndex(new[] { "Code" }, "ix_cable_code_trgm")
                        .HasDatabaseName("ix_cable_code_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Code" }, "ix_cable_code_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Code" }, "ix_cable_code_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("cable", null, t =>
                        {
                            t.HasCheckConstraint("ck_cable_distinct_ends", "a_site_id <> b_site_id");

                            t.HasCheckConstraint("ck_cable_valid_time", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.CableType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("text")
                        .HasColumnName("color_code");

                    b.Property<int>("ConductorCount")
                        .HasColumnType("integer")
                        .HasColumnName("conductor_count");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<CableMedium>("Medium")
                        .HasColumnType("cable_medium")
                        .HasColumnName("medium");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cable_type");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_cable_type_key");

                    b.ToTable("cable_type", null, t =>
                        {
                            t.HasCheckConstraint("ck_cable_type_conductor_count", "conductor_count > 0");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Channel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<ChannelKind>("Kind")
                        .HasColumnType("channel_kind")
                        .HasColumnName("kind");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint")
                        .HasColumnName("terminal_id");

                    b.HasKey("Id")
                        .HasName("pk_channel");

                    b.HasIndex("TerminalId", "Kind", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_terminal_id_kind_number");

                    b.ToTable("channel", null, t =>
                        {
                            t.HasCheckConstraint("ck_channel_number", "number >= 0");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Circuit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("ATerminalId")
                        .HasColumnType("bigint")
                        .HasColumnName("a_terminal_id");

                    b.Property<long>("BTerminalId")
                        .HasColumnType("bigint")
                        .HasColumnName("b_terminal_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<CircuitLayer>("Layer")
                        .HasColumnType("circuit_layer")
                        .HasColumnName("layer");

                    b.Property<LifecycleState>("Lifecycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("lifecycle_state")
                        .HasDefaultValue(LifecycleState.Planned)
                        .HasColumnName("lifecycle");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_circuit");

                    b.HasIndex("ATerminalId")
                        .HasDatabaseName("ix_circuit_a_terminal_id");

                    b.HasIndex("BTerminalId")
                        .HasDatabaseName("ix_circuit_b_terminal_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_circuit_code");

                    b.HasIndex(new[] { "Code" }, "ix_circuit_code_pattern")
                        .HasDatabaseName("ix_circuit_code_pattern");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Code" }, "ix_circuit_code_pattern"), new[] { "text_pattern_ops" });

                    b.HasIndex(new[] { "Code" }, "ix_circuit_code_trgm")
                        .HasDatabaseName("ix_circuit_code_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Code" }, "ix_circuit_code_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Code" }, "ix_circuit_code_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("circuit", null, t =>
                        {
                            t.HasCheckConstraint("ck_circuit_valid_time", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.CircuitDependency", b =>
                {
                    b.Property<long>("CircuitId")
                        .HasColumnType("bigint")
                        .HasColumnName("circuit_id");

                    b.Property<long>("CarrierId")
                        .HasColumnType("bigint")
                        .HasColumnName("carrier_id");

                    b.HasKey("CircuitId", "CarrierId")
                        .HasName("pk_circuit_dependency");

                    b.HasIndex("CarrierId")
                        .HasDatabaseName("ix_circuit_dependency_carrier_id");

                    b.ToTable("circuit_dependency", null, t =>
                        {
                            t.HasCheckConstraint("ck_circuit_dependency_not_self", "circuit_id <> carrier_id");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.CircuitHop", b =>
                {
                    b.Property<long>("CircuitId")
                        .HasColumnType("bigint")
                        .HasColumnName("circuit_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint")
                        .HasColumnName("terminal_id");

                    b.HasKey("CircuitId", "Seq")
                        .HasName("pk_circuit_hop");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_circuit_hop_channel_id");

                    b.HasIndex("TerminalId")
                        .HasDatabaseName("ix_circuit_hop_terminal_id");

                    b.ToTable("circuit_hop", null, t =>
                        {
                            t.HasCheckConstraint("ck_circuit_hop_seq", "seq >= 0");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Conductor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("CableId")
                        .HasColumnType("bigint")
                        .HasColumnName("cable_id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_conductor");

                    b.HasIndex("CableId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_conductor_cable_id_number");

                    b.ToTable("conductor", null, t =>
                        {
                            t.HasCheckConstraint("ck_conductor_number", "number > 0");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.ConductorEnd", b =>
                {
                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint")
                        .HasColumnName("terminal_id");

                    b.Property<long>("ConductorId")
                        .HasColumnType("bigint")
                        .HasColumnName("conductor_id");

                    b.Property<TerminalKind>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("terminal_kind")
                        .HasDefaultValue(TerminalKind.ConductorEnd)
                        .HasColumnName("kind");

                    b.Property<char>("Side")
                        .HasColumnType("char(1)")
                        .HasColumnName("side");

                    b.HasKey("TerminalId")
                        .HasName("pk_conductor_end");

                    b.HasIndex("ConductorId", "Side")
                        .IsUnique()
                        .HasDatabaseName("ix_conductor_end_conductor_id_side");

                    b.HasIndex("TerminalId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_conductor_end_terminal_id_kind");

                    b.ToTable("conductor_end", null, t =>
                        {
                            t.HasCheckConstraint("ck_conductor_end_kind", "kind = 'conductor_end'");

                            t.HasCheckConstraint("ck_conductor_end_side", "side IN ('A', 'B')");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Connection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("ATerminalId")
                        .HasColumnType("bigint")
                        .HasColumnName("a_terminal_id");

                    b.Property<long>("BTerminalId")
                        .HasColumnType("bigint")
                        .HasColumnName("b_terminal_id");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<ConnectionKind>("Kind")
                        .HasColumnType("connection_kind")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<LifecycleState>("Lifecycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("lifecycle_state")
                        .HasDefaultValue(LifecycleState.Planned)
                        .HasColumnName("lifecycle");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_connection");

                    b.HasIndex("BTerminalId")
                        .HasDatabaseName("ix_connection_b_terminal_id");

                    b.HasIndex("ATerminalId", "BTerminalId")
                        .IsUnique()
                        .HasDatabaseName("ix_connection_current_pair")
                        .HasFilter("valid_to IS NULL");

                    b.ToTable("connection", null, t =>
                        {
                            t.HasCheckConstraint("ck_connection_ordered", "a_terminal_id < b_terminal_id");

                            t.HasCheckConstraint("ck_connection_valid_time", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes")
                        .HasDefaultValueSql("'{}'");

                    b.Property<long>("EquipmentTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_type_id");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<LifecycleState>("Lifecycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("lifecycle_state")
                        .HasDefaultValue(LifecycleState.Planned)
                        .HasColumnName("lifecycle");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<long>("SiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("site_id");

                    b.Property<string>("Slot")
                        .HasColumnType("text")
                        .HasColumnName("slot");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.HasIndex("EquipmentTypeId")
                        .HasDatabaseName("ix_equipment_equipment_type_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_equipment_location_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_equipment_site_id");

                    b.HasIndex("ParentId", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_parent_id_slot")
                        .HasFilter("parent_id IS NOT NULL");

                    b.HasIndex(new[] { "Name" }, "ix_equipment_name_trgm")
                        .HasDatabaseName("ix_equipment_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_equipment_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_equipment_name_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("equipment", null, t =>
                        {
                            t.HasCheckConstraint("ck_equipment_not_own_parent", "parent_id IS DISTINCT FROM id");

                            t.HasCheckConstraint("ck_equipment_placement", "(location_id IS NOT NULL) <> (parent_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_equipment_slot", "(parent_id IS NULL) = (slot IS NULL)");

                            t.HasCheckConstraint("ck_equipment_valid_time", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.EquipmentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AttributeSchema")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attribute_schema")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Panel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("panel")
                        .HasDefaultValueSql("'{\"rows\": 1, \"columns\": 1}'");

                    b.Property<string>("PortTemplate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("port_template")
                        .HasDefaultValueSql("'[]'");

                    b.Property<short?>("RackUnits")
                        .HasColumnType("smallint")
                        .HasColumnName("rack_units");

                    b.Property<string>("SlotTemplate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("slot_template")
                        .HasDefaultValueSql("'[]'");

                    b.HasKey("Id")
                        .HasName("pk_equipment_type");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_type_key");

                    b.HasIndex("Manufacturer", "Model")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_type_manufacturer_model");

                    b.ToTable("equipment_type", null, t =>
                        {
                            t.HasCheckConstraint("ck_equipment_type_port_template", "jsonb_typeof(port_template) = 'array'");

                            t.HasCheckConstraint("ck_equipment_type_rack_units", "rack_units > 0");

                            t.HasCheckConstraint("ck_equipment_type_slot_template", "jsonb_typeof(slot_template) = 'array'");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<LifecycleState>("Lifecycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("lifecycle_state")
                        .HasDefaultValue(LifecycleState.Planned)
                        .HasColumnName("lifecycle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<short?>("RackUnits")
                        .HasColumnType("smallint")
                        .HasColumnName("rack_units");

                    b.Property<long>("SiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_location_parent_id");

                    b.HasIndex("SiteId", "ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_location_site_id_parent_id_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("SiteId", "ParentId", "Name"), false);

                    b.ToTable("location", null, t =>
                        {
                            t.HasCheckConstraint("ck_location_kind", "kind IN ('building', 'room', 'rack', 'position')");

                            t.HasCheckConstraint("ck_location_not_own_parent", "parent_id IS DISTINCT FROM id");

                            t.HasCheckConstraint("ck_location_rack_units", "rack_units > 0");

                            t.HasCheckConstraint("ck_location_valid_time", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Port", b =>
                {
                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint")
                        .HasColumnName("terminal_id");

                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_id");

                    b.Property<TerminalKind>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("terminal_kind")
                        .HasDefaultValue(TerminalKind.Port)
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PortGroup")
                        .HasColumnType("text")
                        .HasColumnName("port_group");

                    b.Property<string>("PortType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("port_type");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("TerminalId")
                        .HasName("pk_port");

                    b.HasIndex("EquipmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_port_equipment_id_name");

                    b.HasIndex("TerminalId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_port_terminal_id_kind");

                    b.ToTable("port", null, t =>
                        {
                            t.HasCheckConstraint("ck_port_kind", "kind = 'port'");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<LifecycleState>("Lifecycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("lifecycle_state")
                        .HasDefaultValue(LifecycleState.Planned)
                        .HasColumnName("lifecycle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_service_code");

                    b.HasIndex(new[] { "Code" }, "ix_service_code_pattern")
                        .HasDatabaseName("ix_service_code_pattern");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Code" }, "ix_service_code_pattern"), new[] { "text_pattern_ops" });

                    b.HasIndex(new[] { "Code" }, "ix_service_code_trgm")
                        .HasDatabaseName("ix_service_code_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Code" }, "ix_service_code_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Code" }, "ix_service_code_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "Name" }, "ix_service_name_trgm")
                        .HasDatabaseName("ix_service_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_service_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_service_name_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("service", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_valid_time", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.ServiceCircuit", b =>
                {
                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("CircuitId")
                        .HasColumnType("bigint")
                        .HasColumnName("circuit_id");

                    b.HasKey("ServiceId", "CircuitId")
                        .HasName("pk_service_circuit");

                    b.HasIndex("CircuitId")
                        .HasDatabaseName("ix_service_circuit_circuit_id");

                    b.ToTable("service_circuit", (string)null);
                });

            modelBuilder.Entity("Cmdb.Database.Model.Site", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 3006)")
                        .HasColumnName("geom");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<LifecycleState>("Lifecycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("lifecycle_state")
                        .HasDefaultValue(LifecycleState.Planned)
                        .HasColumnName("lifecycle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SiteType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_type");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_site");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_site_code");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_site_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("SourceSystem", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_site_source_system_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex(new[] { "Code" }, "ix_site_code_pattern")
                        .HasDatabaseName("ix_site_code_pattern");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Code" }, "ix_site_code_pattern"), new[] { "text_pattern_ops" });

                    b.HasIndex(new[] { "Code" }, "ix_site_code_trgm")
                        .HasDatabaseName("ix_site_code_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Code" }, "ix_site_code_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Code" }, "ix_site_code_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "Name" }, "ix_site_name_trgm")
                        .HasDatabaseName("ix_site_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_site_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_site_name_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("site", null, t =>
                        {
                            t.HasCheckConstraint("ck_site_geom_type", "GeometryType(geom) IN ('POINT', 'POLYGON', 'MULTIPOLYGON')");

                            t.HasCheckConstraint("ck_site_valid_time", "valid_to IS NULL OR valid_to > valid_from");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Terminal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<TerminalKind>("Kind")
                        .HasColumnType("terminal_kind")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_terminal");

                    b.HasAlternateKey("Id", "Kind")
                        .HasName("ak_terminals_id_kind");

                    b.ToTable("terminal", (string)null);
                });

            modelBuilder.Entity("Cmdb.Database.Model.UserPreference", b =>
                {
                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("dark")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Subject")
                        .HasName("pk_user_preference");

                    b.ToTable("user_preference", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_preference_theme", "theme IN ('dark', 'light')");
                        });
                });

            modelBuilder.Entity("Cmdb.Database.Model.Cable", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Site", "ASite")
                        .WithMany()
                        .HasForeignKey("ASiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cable_sites_a_site_id");

                    b.HasOne("Cmdb.Database.Model.Site", "BSite")
                        .WithMany()
                        .HasForeignKey("BSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cable_sites_b_site_id");

                    b.HasOne("Cmdb.Database.Model.CableType", "CableType")
                        .WithMany()
                        .HasForeignKey("CableTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cable_cable_types_cable_type_id");

                    b.Navigation("ASite");

                    b.Navigation("BSite");

                    b.Navigation("CableType");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Channel", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_channel_terminals_terminal_id");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Circuit", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Terminal", "ATerminal")
                        .WithMany()
                        .HasForeignKey("ATerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_circuit_terminals_a_terminal_id");

                    b.HasOne("Cmdb.Database.Model.Terminal", "BTerminal")
                        .WithMany()
                        .HasForeignKey("BTerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_circuit_terminals_b_terminal_id");

                    b.Navigation("ATerminal");

                    b.Navigation("BTerminal");
                });

            modelBuilder.Entity("Cmdb.Database.Model.CircuitDependency", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Circuit", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_circuit_dependency_circuit_carrier_id");

                    b.HasOne("Cmdb.Database.Model.Circuit", "Circuit")
                        .WithMany()
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_circuit_dependency_circuit_circuit_id");

                    b.Navigation("Carrier");

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("Cmdb.Database.Model.CircuitHop", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_circuit_hop_channel_channel_id");

                    b.HasOne("Cmdb.Database.Model.Circuit", "Circuit")
                        .WithMany("Hops")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_circuit_hop_circuit_circuit_id");

                    b.HasOne("Cmdb.Database.Model.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_circuit_hop_terminals_terminal_id");

                    b.Navigation("Channel");

                    b.Navigation("Circuit");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Conductor", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Cable", "Cable")
                        .WithMany()
                        .HasForeignKey("CableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conductor_cable_cable_id");

                    b.Navigation("Cable");
                });

            modelBuilder.Entity("Cmdb.Database.Model.ConductorEnd", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conductor_end_conductor_conductor_id");

                    b.HasOne("Cmdb.Database.Model.Terminal", "Terminal")
                        .WithOne()
                        .HasForeignKey("Cmdb.Database.Model.ConductorEnd", "TerminalId", "Kind")
                        .HasPrincipalKey("Cmdb.Database.Model.Terminal", "Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conductor_end_terminals_terminal_id_kind");

                    b.Navigation("Conductor");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Connection", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Terminal", "ATerminal")
                        .WithMany()
                        .HasForeignKey("ATerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_connection_terminals_a_terminal_id");

                    b.HasOne("Cmdb.Database.Model.Terminal", "BTerminal")
                        .WithMany()
                        .HasForeignKey("BTerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_connection_terminals_b_terminal_id");

                    b.Navigation("ATerminal");

                    b.Navigation("BTerminal");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Equipment", b =>
                {
                    b.HasOne("Cmdb.Database.Model.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_equipment_types_equipment_type_id");

                    b.HasOne("Cmdb.Database.Model.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_equipment_locations_location_id");

                    b.HasOne("Cmdb.Database.Model.Equipment", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_equipment_equipment_parent_id");

                    b.HasOne("Cmdb.Database.Model.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_sites_site_id");

                    b.Navigation("EquipmentType");

                    b.Navigation("Location");

                    b.Navigation("Parent");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Location", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Location", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_location_location_parent_id");

                    b.HasOne("Cmdb.Database.Model.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_location_sites_site_id");

                    b.Navigation("Parent");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Port", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Equipment", "Equipment")
                        .WithMany("Ports")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_port_equipment_equipment_id");

                    b.HasOne("Cmdb.Database.Model.Terminal", "Terminal")
                        .WithOne()
                        .HasForeignKey("Cmdb.Database.Model.Port", "TerminalId", "Kind")
                        .HasPrincipalKey("Cmdb.Database.Model.Terminal", "Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_port_terminals_terminal_id_kind");

                    b.Navigation("Equipment");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Cmdb.Database.Model.ServiceCircuit", b =>
                {
                    b.HasOne("Cmdb.Database.Model.Circuit", "Circuit")
                        .WithMany()
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_circuit_circuit_circuit_id");

                    b.HasOne("Cmdb.Database.Model.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_circuit_services_service_id");

                    b.Navigation("Circuit");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Circuit", b =>
                {
                    b.Navigation("Hops");
                });

            modelBuilder.Entity("Cmdb.Database.Model.Equipment", b =>
                {
                    b.Navigation("Ports");
                });
#pragma warning restore 612, 618
        }
    }
}
