<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Cmdb.DataGen</RootNamespace>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\catalog\Cmdb.Catalog.csproj" />
    <ProjectReference Include="..\exchange\Cmdb.Exchange.csproj" />
    <ProjectReference Include="..\database\Cmdb.Database.csproj" />
    <ProjectReference Include="..\graph\Cmdb.Graph.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Cmdb.Api.Tests" />
    <InternalsVisibleTo Include="Cmdb.Api.IntegrationTests" />
    <InternalsVisibleTo Include="Cmdb.Graph.Benchmarks" />
  </ItemGroup>
</Project>
