<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Cmdb.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Cmdb.Api.Tests" />
    <InternalsVisibleTo Include="Cmdb.Api.IntegrationTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\database\Cmdb.Database.csproj" />
    <ProjectReference Include="..\catalog\Cmdb.Catalog.csproj" />
  </ItemGroup>
</Project>
