<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\graph\Cmdb.Graph.csproj" />
    <ProjectReference Include="..\..\src\datagen\Cmdb.DataGen.csproj" />
  </ItemGroup>
</Project>
